version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeJcMultiStepDemoAPI4Gartner
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter/EdgeJcMultiStepDemoAPI4Gartner
  gitUsername: johnpcarter
  gitToken: edge.scaffolding.EdgeJcMultiStepDemoAPI4Gartner.johnpcarter.gitToken
  gitBranch: main
